services:
  market.api:
    image: market.api
    build:
      context: .
      dockerfile: src/Market.API/Dockerfile
      
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: src/UsersApi/Dockerfile